[package]
name = "byte-unit"
version = "4.0.6"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/byte-unit"
homepage = "https://magiclen.org/byte-unit"
keywords = ["byte", "unit", "kb", "mb", "gb"]
categories = ["no-std", "parser-implementations", "value-formatting"]
description= "A library for interaction with units of bytes."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml"]

[badges.travis-ci]
repository = "magiclen/Byte-Unit"
branch = "master"

[dependencies]
serde = { version = "1", optional = true }

[features]
default = ["std", "u128"]
std = []
u128 = []